### ISSUE TITLE
Plugin checklist

### ISSUE THREAD

**Issue by devbridie** [devbridie/unjquerify#1]
- [ ] [1.0 Query by selector](https://github.com/nefe/You-Dont-Need-jQuery#1.0)
 - [ ] [1.1 Query by class](https://github.com/nefe/You-Dont-Need-jQuery#1.1)
 - [ ] [1.2 Query by id](https://github.com/nefe/You-Dont-Need-jQuery#1.2)
 - [ ] [1.3 Query by attribute](https://github.com/nefe/You-Dont-Need-jQuery#1.3)
 - [ ] [1.4 Query in descendants](https://github.com/nefe/You-Dont-Need-jQuery#1.4)
 - [ ] [1.5 Sibling/Previous/Next Elements](https://github.com/nefe/You-Dont-Need-jQuery#1.5)
 - [ ] [1.6 Closest](https://github.com/nefe/You-Dont-Need-jQuery#1.6)
 - [ ] [1.7 Parents Until](https://github.com/nefe/You-Dont-Need-jQuery#1.7)
 - [ ] [1.8 Form](https://github.com/nefe/You-Dont-Need-jQuery#1.8)
 - [ ] [1.9 Iframe Contents](https://github.com/nefe/You-Dont-Need-jQuery#1.9)
 - [ ] [1.10 Get body](https://github.com/nefe/You-Dont-Need-jQuery#1.10)
 - [ ] [1.11 Attribute getter and setter](https://github.com/nefe/You-Dont-Need-jQuery#1.11)
 - [ ] [1.12 Selector containing string (case-sensitive)](https://github.com/nefe/You-Dont-Need-jQuery#1.12)
 - [ ] [2.1 CSS](https://github.com/nefe/You-Dont-Need-jQuery#2.1)
 - [ ] [2.2 Width & Height](https://github.com/nefe/You-Dont-Need-jQuery#2.2)
 - [ ] [2.3 Position & Offset](https://github.com/nefe/You-Dont-Need-jQuery#2.3)
 - [ ] [2.4 Scroll Top](https://github.com/nefe/You-Dont-Need-jQuery#2.4)
 - [ ] [3.1 Remove](https://github.com/nefe/You-Dont-Need-jQuery#3.1)
 - [ ] [3.2 Text](https://github.com/nefe/You-Dont-Need-jQuery#3.2)
 - [ ] [3.3 HTML](https://github.com/nefe/You-Dont-Need-jQuery#3.3)
 - [ ] [3.4 Append](https://github.com/nefe/You-Dont-Need-jQuery#3.4)
 - [ ] [3.5 Prepend](https://github.com/nefe/You-Dont-Need-jQuery#3.5)
 - [ ] [3.6 insertBefore](https://github.com/nefe/You-Dont-Need-jQuery#3.6)
 - [ ] [3.7 insertAfter](https://github.com/nefe/You-Dont-Need-jQuery#3.7)
 - [ ] [3.8 is](https://github.com/nefe/You-Dont-Need-jQuery#3.8)
 - [ ] [3.9 clone](https://github.com/nefe/You-Dont-Need-jQuery#3.9)
 - [ ] [3.10 empty](https://github.com/nefe/You-Dont-Need-jQuery#3.10)
 - [ ] [3.11 wrap](https://github.com/nefe/You-Dont-Need-jQuery#3.11)
 - [ ] [3.12 unwrap](https://github.com/nefe/You-Dont-Need-jQuery#3.12)
 - [ ] [3.13 replaceWith](https://github.com/nefe/You-Dont-Need-jQuery#3.13)
 - [ ] [3.14 simple parse](https://github.com/nefe/You-Dont-Need-jQuery#3.14)
 - [ ] [4.1 Load data from the server and place the returned HTML into the matched element.](https://github.com/nefe/You-Dont-Need-jQuery#4.1)
 - [ ] [5.0 Document ready by DOMContentLoaded](https://github.com/nefe/You-Dont-Need-jQuery#5.0)
 - [ ] [5.1 Bind an event with on](https://github.com/nefe/You-Dont-Need-jQuery#5.1)
 - [ ] [5.2 Unbind an event with off](https://github.com/nefe/You-Dont-Need-jQuery#5.2)
 - [ ] [5.3 Trigger](https://github.com/nefe/You-Dont-Need-jQuery#5.3)
 - [ ] [6.1 Basic utilities](https://github.com/nefe/You-Dont-Need-jQuery#6.1)
 - [ ] [6.2 Contains](https://github.com/nefe/You-Dont-Need-jQuery#6.2)
 - [ ] [6.3 Globaleval](https://github.com/nefe/You-Dont-Need-jQuery#6.3)
 - [ ] [6.4 parse](https://github.com/nefe/You-Dont-Need-jQuery#6.4)
 - [ ] [7.1 done, fail, always](https://github.com/nefe/You-Dont-Need-jQuery#7.1)
 - [ ] [7.2 when](https://github.com/nefe/You-Dont-Need-jQuery#7.2)
 - [ ] [7.3 Deferred](https://github.com/nefe/You-Dont-Need-jQuery#7.3)
 - [ ] [8.1 Show & Hide](https://github.com/nefe/You-Dont-Need-jQuery#8.1)
 - [ ] [8.2 Toggle](https://github.com/nefe/You-Dont-Need-jQuery#8.2)
 - [ ] [8.3 FadeIn & FadeOut](https://github.com/nefe/You-Dont-Need-jQuery#8.3)
 - [ ] [8.4 FadeTo](https://github.com/nefe/You-Dont-Need-jQuery#8.4)
 - [ ] [8.5 FadeToggle](https://github.com/nefe/You-Dont-Need-jQuery#8.5)
 - [ ] [8.6 SlideUp & SlideDown](https://github.com/nefe/You-Dont-Need-jQuery#8.6)
 - [ ] [8.7 SlideToggle](https://github.com/nefe/You-Dont-Need-jQuery#8.7)
 - [ ] [8.8 Animate](https://github.com/nefe/You-Dont-Need-jQuery#8.8)
